name: Pulumi

on:
  push:
    branches:
      - "main"
    paths:
      - "iac/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "iac/**"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  skip-duplicate-actions:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: true
          concurrent_skipping: never

  pulumi-actions:
    name: Pulumi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go latest
        uses: actions/setup-go@v3
        with:
          go-version: stable

      - name: Download package dependencies
        run: go mod download
        working-directory: iac

      - name: Pulumi preview
        env:
          GITHUB_OWNER: ${{ github.repository_owner }}
          PULUMI_CONFIG_PASSPHRASE: ""
          PULUMI_SKIP_UPDATE_CHECK: true
        run: |
          pulumi login --local
          pulumi stack init --stack=stack
          pulumi plugin install resource github
          pulumi config set github:token ${{ secrets.GITHUB_TOKEN }} --secret
          pulumi config set github:owner ${{ env.GITHUB_OWNER }} --secret
          pulumi preview --debug --diff --non-interactive
        working-directory: iac
