name: Pulumi-Actions

on:
  push:
    branches:
      - "main"
    paths:
      - "iac/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "iac/**"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  skip-duplicate-actions:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: true
          concurrent_skipping: never

  pulumi-actions:
    name: Pulumi-Automation-API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: stable

      - name: Download package dependencies
        run: go mod download
        working-directory: iac

      - name: Pulumi-Actions
        uses: pulumi/actions@v4
        with:
          cloud-url: file://~
          command: preview
          comment-on-pr: true
          diff: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          stack-name: test
          upsert: true
          work-dir: iac
